### PR TITLE
Add log flume lifthill sound

### PR DESCRIPTION
**Pull request by karst**
I got it on a nice volume level and looping correctly. I like the overall feel it gives to the log flume and makes it more of a present ride. This was supposed to go to [OpenRCT2#20258](https://github.com/OpenRCT2/OpenRCT2/pull/20258), but I might decide to make a seperate PR for it.

Requires the updating of `audio.h` on the OpenRCT2 main repo.

In my test PR I called this  LiftFlume (Row 133): https://github.com/karst/OpenRCT2/tree/log-flume-sound

### CODE REVIEW

**Review by tupaschoal — COMMENTED** [review]
I like it, always felt weird that log flumes would be completely silent uphill

> I got it on a nice volume level and looping correctly.
Was this extracted from somewhere? I was a bit confused

**Comment by karst** [comment]
i had it ready a few months ago already, but never published it. It wasn't looping correctly and it was a tad loud. 

That makes me think i should probably go over all sfx again sometime to adjust them, especially the toilet sound apparently that's way too loud for people 😂

**Review by tupaschoal — APPROVED** [review]
I think it deserves its own PR on OpenRCT2/OpenRCT2, it's a simpler change, so it doesn't get dragged with the other PR.

**Comment by karst** [comment]
The only issue will be that it will only be audible on currently cheated in lifthills. Ofcourse the other PR will take care of that.

**Pull request merged**
